name = "internet"
type = "javascript" # <- baris penting, ini harus ada
main = "api/index.js"
compatibility_date = "2024-12-30"

[site]
bucket = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "internet"
database_id = "bff89823-71c1-40b9-93d3-7fa1b9abbd7a"

[env.production]
workers_dev = true
